- package-lock.json
- package.json
Angular versions matching now. Also changed network configuration to allow for connection.
> Able to host portfolio

- CHANGELOG.md
- package-lock.json
- package.json
Initial changelog and version commit
> Add version management

- .github/workflows/node.js.yml
- CHANGELOG.md
- karma.conf.js
- package-lock.json
- package.json
- src/app/app.component.html
- src/app/app.component.spec.ts
Adding node js CI to build and test for each pull request.
> feat: Add github CI

- angular.json
- src/app/hero-section/hero-section.component.html
- src/app/hero-section/hero-section.component.ts
- src/scripts.js
- src/styles.css
This allows for switching between colors on the fly ( a later feature )
Also added some JS functions to switch between color schemes in order to test functionality.
> Added CSS variables for colorscheme

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/hero-section/hero-section.component.css
- src/app/hero-section/hero-section.component.html
- src/index.html
This completes the implementation of the design for the first section, the hero section. Be sure to compare against the figma design to make sure it matches.
> Adds threejs particle effect

- src/app/hero-section/hero-section.component.css
Add background color to increase contrast.
> 55 add background to scroll indicator

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/hero-section/hero-section.component.css
final adjustment to complete hero section
> Adjust hero typography position

- src/app/app.component.css
- src/app/app.component.html
- src/app/experience-section/experience-section.component.css
- src/app/experience-section/experience-section.component.html
- src/styles.css
Adds static structure for experience section
> Add experience section

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/about-section/about-section.component.html
- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/experience-section/experience-section.component.css
- src/app/experience-section/experience-section.component.html
- src/app/experience-section/experience-section.component.spec.ts
- src/app/experience-section/experience-section.component.ts
You can now select different work experiences by clicking on them! This will change the experience that is visible.
UX and animations for doing this still need to be implemented. That will be handled in another milestone.
Also added some unit testing.
> Implement experience switching

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/navbar/navbar.component.css
- src/styles.css
now follows along as you scroll.
> Navbar is not fixed position

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/app.component.html
- src/app/contact-section/contact-section.component.css
- src/app/contact-section/contact-section.component.html
- src/styles.css
Implemented typography. No highlight color on email since it doesn't make sense from a UI design perspective. Will likely be handled in the CSS animations milestone.
> Implement contact section typography

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/contact-section/contact-section.component.css
- src/app/contact-section/contact-section.component.html
- src/assets/js/Clock.js
- src/index.html
Ticking clock has Atlantic Timezone set for users outside of my timezone
> Implement contact section clock

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/color-switcher/color-switcher.component.css
- src/app/color-switcher/color-switcher.component.html
- src/app/hero-section/hero-section.component.css
- src/styles.css
> 84 fix scrollbar background color

- CHANGELOG.md
- package-lock.json
- package.json
- scripts/deploy.js
- src/app/about-section/about-section.component.css
- src/app/app.component.spec.ts
- src/app/contact-section/contact-section.component.css
- src/app/contact-section/contact-section.component.html
- src/app/experience-section/experience-section.component.css
- src/app/experience-section/experience-section.component.spec.ts
- src/app/experience-section/experience-section.component.ts
- src/app/hero-section/hero-section.component.css
- src/app/hero-section/hero-section.component.html
- src/app/navbar/navbar.component.css
- src/styles.css
View with window width of 1020 and observe design changes to fit new width.
> Implement tablet layout media queries

- src/app/experience-section/experience-section.component.css
- src/app/experience-section/experience-section.component.html
- src/styles.css
helps mobile UX so that users know to scroll
> feat(UI): Add scroll arrow to experience scroller

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/color-switcher/color-switcher.component.css
- src/app/color-switcher/color-switcher.component.html
- src/app/color-switcher/color-switcher.component.ts
- src/assets/js/ChangeColors.js
- src/assets/js/HeroAnimation.js
- src/styles.css
The color switcher now works for the most part. There is a minor bug with an element that uses a linear-gradient (these do not support color CSS transitions yet). That will be handled as a bug in a separate issue.
> implement color switcher functionality

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/hero-section/hero-section.component.css
- src/app/hero-section/hero-section.component.html
- src/assets/js/HeroAnimation.js
I refactored the hero animation to be more maintainable and have a more intelligent implementation. This allows for the following:
- Row-based control of particle position & color
- No need to massively overflow particles to ensure the main area is filled
> 118 refactor hero animation

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/hero-section/hero-section.component.css
- src/styles.css
made the arrow shorter and did a quick refactor to be more stable on different screen heights.
> Scroll arrow too tall for screen width 833px

- src/app/experience-section/experience-section.component.css
color changes instantly no matter what.
> Remove experience switcher color transition

- src/app/about-section/about-section.component.css
slight adjustments to the headshot size for every media query. I think the phone view was the most off.
> Ensure headshot is properly sized

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/about-section/about-section.component.html
- src/app/contact-section/contact-section.component.html
- src/app/experience-section/experience-section.component.html
- src/app/navbar/navbar.component.css
- src/app/navbar/navbar.component.html
- src/assets/js/Navbar.js
- src/index.html
Navbar now works! you can click on links and they will scroll you to the appropriate section on the webpage. Color of the currently active section is also highlighted.
> Implement navbar functionality

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/contact-section/contact-section.component.css
- src/app/contact-section/contact-section.component.html
- src/styles.css
Implements the contact section.
> Implement contact links

- src/app/about-section/about-section.component.html
- src/app/contact-section/contact-section.component.css
- src/app/contact-section/contact-section.component.html
- src/app/experience-section/experience-section.component.html
- src/app/navbar/navbar.component.html
- src/assets/js/Navbar.js
HTML Elements were larger than the screen, so was unable to detect if they were within the users viewport. Used smaller elements and now works.
> Fixed navbar on mobile screens

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/app.component.html
- src/app/app.component.spec.ts
- src/app/app.module.ts
- src/app/utility-components/preloader/preloader.component.css
- src/app/utility-components/preloader/preloader.component.html
- src/app/utility-components/preloader/preloader.component.spec.ts
- src/app/utility-components/preloader/preloader.component.ts
- src/assets/js/Preloader.js
- src/index.html
Animation has been added, solves several other bugs.
> Add website loading animation

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/structural-components/experience-section/experience-section.component.css
- src/app/structural-components/experience-section/experience-section.component.html
- src/app/structural-components/experience-section/experience-section.component.spec.ts
- src/app/structural-components/experience-section/experience-section.component.ts
- src/app/utility-components/preloader/preloader.component.css
- src/assets/js/ChangeColors.js
- src/styles.css
Make the experience switcher smaller than the experience detail section in order to preserve visual hierarchy. It was way too big before.
> Make experience switcher smaller

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/structural-components/experience-section/experience-section.component.css
- src/app/structural-components/experience-section/experience-section.component.html
- src/app/structural-components/experience-section/years-display/years-display.component.css
- src/app/structural-components/experience-section/years-display/years-display.component.html
- src/app/structural-components/experience-section/years-display/years-display.component.spec.ts
- src/app/structural-components/experience-section/years-display/years-display.component.ts
- src/assets/js/scrollAnimations.js
- src/styles.css
adds a simple scroll animation for the title that is borrowed from the About section. Also adds a new visual element that displays how many years of work experience I have.
> Add scroll animation for experience section

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/app.component.spec.ts
- src/app/structural-components/about-section/about-section.component.html
- src/app/structural-components/contact-section/contact-section.component.html
- src/app/structural-components/experience-section/experience-section.component.spec.ts
- src/app/structural-components/experience-section/experience-section.component.ts
- src/app/structural-components/hero-section/hero-section.component.html
I went into each section and improve on the grammar, correct any spelling mistakes, or re-write to make it clearer.
> Revisit wording for sections

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/app.component.html
- src/app/app.module.ts
- src/app/utility-components/version-number/version-number.component.css
- src/app/utility-components/version-number/version-number.component.html
- src/app/utility-components/version-number/version-number.component.spec.ts
- src/app/utility-components/version-number/version-number.component.ts
- tsconfig.json
Adds a small textbox for version number in the bottom right corner of the screen
> 144 add version number

- CHANGELOG.md
- package-lock.json
- package.json
- src/styles.css
small feature, does not add much
> Add smooth scrolling

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/structural-components/experience-section/experience-section.component.html
- src/styles.css
quality of life and tech debt improvement
> Refactor scroll animations to use translate

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/app.component.spec.ts
- src/app/structural-components/experience-section/experience-section.component.html
- src/app/structural-components/experience-section/experience-section.component.spec.ts
- src/app/structural-components/experience-section/experience-section.component.ts
- src/app/structural-components/experience-section/experience.ts
Create a class that contains the data for a work experience. Initializes a bunch of classes with the data at the start, and uses those classes to load experience data into the component.
> Refactor experience section implementation

- src/app/structural-components/contact-section/contact-section.component.css
> Make time text not bold

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/structural-components/about-section/about-section.component.html
- src/app/structural-components/experience-section/experience-section.component.css
Flex scrum master certification. Lazy way to add it right now. Will improve in further versions.
> 172 add scrum master certification

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/structural-components/contact-section/contact-section.component.css
- src/app/structural-components/contact-section/contact-section.component.html
- src/app/structural-components/experience-section/experience-section.component.css
- src/app/structural-components/navbar/navbar.component.css
- src/app/structural-components/navbar/navbar.component.html
- src/assets/js/Navbar.js
- src/styles.css
Matches the highlight effect in the contact section for consistency.
> Add highlight effect to nav links

- CHANGELOG.md
- package-lock.json
- package.json
Final quality of life and user experience changes before website is considered complete!
> update version to 1.0.0

- src/app/structural-components/navbar/navbar.component.css
- src/app/structural-components/navbar/navbar.component.html
- src/assets/js/Navbar.js
old effect was buggy and confusing. Making this more simple saves complexity and offers a less buggy experience
> Remove old hover effect added to navbar

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/structural-components/experience-section/experience-section.component.css
- src/app/structural-components/experience-section/experience-section.component.html
- src/app/structural-components/navbar/navbar.component.css
- src/app/structural-components/navbar/navbar.component.html
- src/assets/js/Navbar.js
- src/styles.css
Moves numbers to the navbar. Big improvement to UI design in my opinion.
> Move indicator numbers from experience section to navbar

- src/app/structural-components/navbar/navbar.component.css
This reverts commit bdae26884949300d0915c3cb1fb3ce8afd9c1bc1.
The addition of semibold Looks wrong.
> Revert "fix: add semibold to navar"

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/structural-components/about-section/about-section.component.html
- src/app/structural-components/experience-section/experience-section.component.css
- src/app/structural-components/experience-section/experience.ts
Generally update wording now that I have a better idea of my position and what I will be doing going forward.
> Update arctic wolf experience

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/structural-components/about-section/about-section.component.html
Makes design more consistent IMO
> Change arrows in about sections to squarescircles

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/structural-components/about-section/about-section.component.html
> 188 make website appear higher on google search results

- CHANGELOG.md
- package-lock.json
- package.json
- src/assets/js/HeroAnimation.js
Tweaked animation so that it's less expensive on mobile devices. I wanted to disable it entirely, but doing so makes the animation break if you resize from mobile to desktop views.
> 204 disable hero animation on mobile views

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/structural-components/hero-section/hero-section.component.css
- src/app/structural-components/hero-section/hero-section.component.html
- src/assets/js/ChangeColors.js
- src/assets/js/HeroAnimation.js
- src/index.html
I refactored the whole animation to use an OOP framework, which allows for a lot more efficiency and future features. It's been massively improved!
> 186 fix hero animation for different resolutions 1440p

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/structural-components/experience-section/years-display/years-display.component.html
- src/assets/js/YearsOfExperience.js
- src/index.html
Automatically calculate the number of years of experience I have so I don't have to do this again next year. 
Also changed the format of this section so it reads left-to-right.
> Update years of experience to be automated

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/structural-components/experience-section/experience-section.component.ts
- src/app/structural-components/experience-section/experience.ts
Reworded this section to be more up to date with my current experience
> 218 update experience section

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/structural-components/contact-section/contact-section.component.css
- src/app/structural-components/contact-section/contact-section.component.html
- src/assets/js/copyEmail.js
- src/index.html
This PR adds the ability to copy emails to the users clipboard just by pressing on the copy button!
> 214: implement flow fields in hero animation
